name: Run Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Code linting & Unit tests
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Linting code
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.52
          args: --timeout=10m0s
      - name: Start Redis instance
        run: docker run -d -p 6379:6379 --name redis -e REDIS_PASSWORD=password123 bitnami/redis:6.2
      - name: Test
        run: make test
        env:
          TEST_REDIS_ADDR: "127.0.0.1:6379"
          TEST_REDIS_PASS: "password123"
          TEST_REDIS_DB: 0
  test-e2e-gofer:
    name: E2E Tests (Gofer)
    strategy:
      matrix:
        go-version: [ 1.20.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download vendors
        run: go mod vendor
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Run E2E Tests
        working-directory: ./e2e
        run: go test -v -p 1 -run ^Test_Gofer
  test-e2e-ghost:
    name: E2E Tests (Ghost)
    strategy:
      matrix:
        go-version: [ 1.20.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download vendors
        run: go mod vendor
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Run E2E Tests
        working-directory: ./e2e
        run: go test -v -p 1 -run ^Test_Ghost
  test-e2e-teleport:
    name: E2E Tests (Teleport)
    strategy:
      matrix:
        go-version: [ 1.20.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download vendors
        run: go mod vendor
      - name: Start Smocker instance for testing
        run: docker run -d -p 8080:8080 -p 8081:8081 --name smocker thiht/smocker
      - name: Run E2E Tests
        working-directory: ./e2e
        run: go test -v -p 1 -run ^Test_Teleport
